import re

path = "update_seo.py"

new_slugs = '''  "chicken-and-zucchini": {
    title: "6 Easy Recipes with Chicken and Zucchini (Quick Weeknight Dinners)",
    heading: "6 Easy Recipes with Chicken and Zucchini",
    intro: "Chicken and zucchini is a light, healthy combination that comes together in under 30 minutes. Zucchini soaks up flavors beautifully and pairs naturally with chicken in stir fries, sheet pan dinners, pasta dishes, and more. Both ingredients are low in calories and high in nutrients, making this one of the best clean-eating combos you can cook at home. Whether you are trying to eat healthier or just use up the zucchini sitting in your fridge, these recipes deliver big flavor with minimal effort.",
    ingredients: "chicken,zucchini",
    keywords: ["chicken and zucchini recipes", "easy chicken zucchini dinner", "healthy chicken zucchini meals", "chicken zucchini stir fry", "quick chicken and zucchini"],
    tips: [
      "Do not overcook zucchini — it only needs 3 to 4 minutes in a hot pan to become tender.",
      "Salt zucchini and let it sit for 10 minutes before cooking to draw out excess moisture.",
      "Cut chicken and zucchini into similar-sized pieces for even cooking.",
      "Use high heat for stir frying to get a light char on the zucchini rather than steaming it.",
      "Add lemon zest at the end of cooking to brighten the flavors of both chicken and zucchini.",
    ],
    variations: [
      "Sheet pan version: Toss with olive oil, garlic, and Italian seasoning, roast at 425F for 20 minutes.",
      "Stir fry version: Cook with soy sauce, ginger, and sesame oil for an Asian-inspired meal.",
      "Pasta version: Toss with cooked pasta, cherry tomatoes, and parmesan for a light summer dish.",
      "Stuffed version: Hollow out zucchini halves, fill with seasoned ground chicken, and bake at 375F.",
      "Soup version: Add chicken broth, diced tomatoes, and white beans for a hearty Italian-style soup.",
    ],
    faqs: [
      { q: "Do I need to peel zucchini before cooking?", a: "No, the skin is tender and edible. Just wash it well and trim the ends. Peeling is only necessary if the zucchini is very large and the skin has become tough." },
      { q: "Can I use yellow squash instead of zucchini?", a: "Yes, yellow squash is nearly identical in flavor and texture and can be swapped 1 for 1 in any chicken and zucchini recipe." },
      { q: "How do I prevent chicken and zucchini from getting watery?", a: "Salt the zucchini ahead of time and pat dry before cooking. Use high heat and avoid crowding the pan so moisture evaporates quickly." },
      { q: "What seasoning goes best with chicken and zucchini?", a: "Italian herbs like oregano, basil, and thyme work beautifully. Garlic, lemon, and red pepper flakes are also classic pairings that enhance both ingredients." },
    ],
  },
  "chicken-and-sweet-potato": {
    title: "6 Easy Recipes with Chicken and Sweet Potato (Healthy & Hearty)",
    heading: "6 Easy Recipes with Chicken and Sweet Potato",
    intro: "Chicken and sweet potato is a winning combination that is as nutritious as it is delicious. Sweet potatoes add natural sweetness, fiber, and vitamins to any chicken dish, making meals that are satisfying and good for you. From sheet pan dinners to warming stews and curries, this pairing works across a huge range of cuisines and cooking styles. If you have chicken and sweet potatoes at home, you are just 30 minutes away from a complete, wholesome meal.",
    ingredients: "chicken,sweet potato",
    keywords: ["chicken and sweet potato recipes", "easy chicken sweet potato dinner", "healthy chicken sweet potato meals", "chicken sweet potato bake", "chicken and sweet potato curry"],
    tips: [
      "Cut sweet potatoes into evenly sized cubes so they roast or cook at the same rate.",
      "Parboil sweet potato cubes for 5 minutes before roasting to cut oven time significantly.",
      "Sweet potatoes pair beautifully with warming spices like cumin, smoked paprika, and cinnamon.",
      "Use bone-in chicken thighs for sheet pan dinners — they stay juicier alongside sweet potatoes.",
      "Roast at high heat (425F) to caramelize the sweet potatoes and get crispy chicken skin.",
    ],
    variations: [
      "Sheet pan version: Season with smoked paprika and garlic, roast together at 425F for 35 minutes.",
      "Curry version: Simmer in coconut milk with curry powder, ginger, and garlic for a warming stew.",
      "Stuffed version: Bake sweet potatoes whole, then top with seasoned shredded chicken and cheese.",
      "Soup version: Blend roasted sweet potato with chicken broth and spices for a creamy soup.",
      "Bowl version: Serve roasted chicken and sweet potato over quinoa with a tahini dressing.",
    ],
    faqs: [
      { q: "Do sweet potatoes and chicken cook at the same rate?", a: "Not always — sweet potatoes take longer. Cut them smaller than the chicken pieces or give them a 10 to 15 minute head start in the oven before adding the chicken." },
      { q: "What spices go best with chicken and sweet potato?", a: "Smoked paprika, cumin, garlic powder, cinnamon, and chili powder all complement both ingredients. For an Asian twist, try five spice or ginger." },
      { q: "Can I meal prep chicken and sweet potato?", a: "Yes, it is an excellent meal prep combination. Cook a large batch and store in the fridge for up to 4 days. It reheats well in the microwave or oven." },
      { q: "Is chicken and sweet potato good for weight loss?", a: "Yes, it is a high-protein, high-fiber meal that keeps you full. Sweet potatoes have a lower glycemic index than white potatoes and are packed with vitamins A and C." },
    ],
  },
  "ground-beef-and-onions": {
    title: "6 Easy Recipes with Ground Beef and Onions (Budget-Friendly Dinners)",
    heading: "6 Easy Recipes with Ground Beef and Onions",
    intro: "Ground beef and onions are two of the most essential ingredients in any kitchen. Together they form the flavor base for hundreds of classic dishes — burgers, Bolognese, shepherd's pie, tacos, and so much more. Onions caramelize beautifully with ground beef, adding sweetness and depth that elevates even the simplest recipe. Best of all, this combination is incredibly budget-friendly and quick to cook. If you have ground beef and onions on hand, a great dinner is never far away.",
    ingredients: "ground beef,onions",
    keywords: ["ground beef and onion recipes", "easy ground beef onion dinner", "ground beef onion skillet", "simple ground beef meals", "budget ground beef recipes"],
    tips: [
      "Cook onions first over medium heat until softened before adding ground beef for the best flavor.",
      "Use 80/20 ground beef for the most flavor — the fat keeps the meat moist and tasty.",
      "Break ground beef into small pieces as it cooks for even browning and better texture.",
      "Drain excess fat after browning for a less greasy final dish.",
      "Caramelize onions slowly over low heat for 20 minutes to develop deep, sweet flavor.",
    ],
    variations: [
      "Burger version: Mix beef and onions together, form patties, and grill or pan fry until cooked through.",
      "Bolognese version: Add canned tomatoes, garlic, and Italian herbs, simmer 30 minutes and serve over pasta.",
      "Shepherd's pie version: Top seasoned beef and onion mixture with mashed potatoes and bake until golden.",
      "Taco version: Season with cumin, chili powder, and garlic, serve in tortillas with your favorite toppings.",
      "Skillet version: Add diced potatoes and bell peppers for a complete one-pan hash dinner.",
    ],
    faqs: [
      { q: "What type of onion is best with ground beef?", a: "Yellow onions are the most versatile and work in nearly every ground beef recipe. White onions have a sharper flavor good for Mexican dishes. Sweet onions like Vidalia are great for caramelizing." },
      { q: "How do I stop ground beef from clumping?", a: "Break it up immediately as it hits the pan using a wooden spoon or spatula. Do not overcrowd the pan and use medium-high heat to brown rather than steam the meat." },
      { q: "Can I freeze cooked ground beef and onions?", a: "Yes, it freezes very well. Cool completely, store in an airtight container or freezer bag, and freeze for up to 3 months. Thaw overnight in the fridge before reheating." },
      { q: "How long does cooked ground beef last in the fridge?", a: "Cooked ground beef stored in an airtight container will last 3 to 4 days in the refrigerator. Always reheat to an internal temperature of 165F before eating." },
    ],
  },
  "shrimp-and-garlic": {
    title: "6 Easy Recipes with Shrimp and Garlic (Quick & Flavorful Dinners)",
    heading: "6 Easy Recipes with Shrimp and Garlic",
    intro: "Shrimp and garlic is one of the most classic and beloved flavor combinations in cooking. Garlic butter shrimp, shrimp scampi, garlic shrimp pasta — these dishes are restaurant favorites that you can easily make at home in under 20 minutes. Shrimp cooks incredibly fast, which makes it the perfect protein for busy weeknights. Paired with the bold, aromatic flavor of garlic, you get a meal that tastes impressive with very little effort. Here are the best easy shrimp and garlic recipes to try tonight.",
    ingredients: "shrimp,garlic",
    keywords: ["shrimp and garlic recipes", "garlic butter shrimp recipe", "easy shrimp garlic dinner", "shrimp scampi recipe", "quick shrimp and garlic meals"],
    tips: [
      "Do not overcook shrimp — it only takes 2 to 3 minutes per side and turns rubbery when overdone.",
      "Pat shrimp completely dry before cooking to get a better sear in the pan.",
      "Use fresh garlic rather than garlic powder for the best flavor in shrimp dishes.",
      "Cook garlic in butter over medium heat until fragrant before adding shrimp — about 30 seconds.",
      "Add a splash of white wine or lemon juice to deglaze the pan and build a simple sauce.",
    ],
    variations: [
      "Garlic butter version: Cook shrimp in butter with minced garlic and finish with lemon juice and parsley.",
      "Scampi version: Add white wine, lemon, and butter to garlic shrimp and serve over linguine.",
      "Stir fry version: Toss with soy sauce, ginger, and vegetables for a quick Asian-style meal.",
      "Grilled version: Thread onto skewers with garlic oil, grill 2 minutes per side, serve with crusty bread.",
      "Pasta version: Toss garlic shrimp with cooked pasta, olive oil, chili flakes, and parmesan.",
    ],
    faqs: [
      { q: "Should I use fresh or frozen shrimp?", a: "Both work well. Frozen shrimp is often fresher than fresh shrimp at the store since it is frozen at sea. Thaw overnight in the fridge or under cold running water for 10 minutes before cooking." },
      { q: "What size shrimp is best for garlic shrimp?", a: "Large or jumbo shrimp (16 to 20 count per pound) work best as they are easier to cook without overdoing and have more flavor than smaller shrimp." },
      { q: "Can I make garlic shrimp ahead of time?", a: "Shrimp is best eaten fresh as it can become rubbery when reheated. If needed, undercook slightly, refrigerate, and reheat gently in a pan over low heat for 1 to 2 minutes." },
      { q: "What goes well with garlic shrimp?", a: "Pasta, crusty bread, rice, or a simple green salad all pair beautifully. Roasted asparagus or sauteed spinach also make excellent sides." },
    ],
  },
  "salmon-and-potatoes": {
    title: "6 Easy Recipes with Salmon and Potatoes (Healthy & Filling Dinners)",
    heading: "6 Easy Recipes with Salmon and Potatoes",
    intro: "Salmon and potatoes is a classic, hearty combination that works beautifully in everything from simple sheet pan dinners to elegant fish cakes. Salmon is one of the healthiest proteins you can eat, rich in omega-3 fatty acids, while potatoes provide satisfying carbohydrates and a neutral base that complements the rich flavor of the fish. Together they make a complete, balanced meal that is surprisingly easy to prepare at home. Here are the best easy salmon and potato recipes for any night of the week.",
    ingredients: "salmon,potatoes",
    keywords: ["salmon and potato recipes", "easy salmon potato dinner", "salmon potato bake", "healthy salmon meals", "salmon and roasted potatoes"],
    tips: [
      "Start potatoes in the oven before the salmon since they take longer to cook.",
      "Pat salmon dry and season generously with salt just before cooking for a better crust.",
      "Cook salmon skin-side down first in a hot pan for crispy skin.",
      "Fingerling or baby potatoes roast faster and taste great alongside salmon.",
      "A simple lemon and dill seasoning complements both salmon and potatoes perfectly.",
    ],
    variations: [
      "Sheet pan version: Roast seasoned potato wedges for 20 minutes, add salmon fillets and cook 12 more minutes.",
      "Fish cake version: Mix flaked cooked salmon with mashed potato, form patties, and pan fry until golden.",
      "Chowder version: Simmer salmon and diced potatoes in cream with dill and leek for a hearty soup.",
      "Salad version: Combine flaked salmon with boiled potatoes, capers, and a mustard dressing.",
      "Foil pack version: Wrap salmon and potato slices with lemon and herbs, bake at 400F for 25 minutes.",
    ],
    faqs: [
      { q: "What type of potato works best with salmon?", a: "Yukon Gold potatoes have a buttery flavor that pairs beautifully with salmon. Baby or fingerling potatoes roast quickly and look elegant. Russets work well for mashing or making fish cakes." },
      { q: "How do I know when salmon is cooked through?", a: "Salmon is done when it flakes easily with a fork and the flesh has turned from translucent to opaque. The internal temperature should reach 145F. For a silkier texture, pull it at 125 to 130F." },
      { q: "Can I use canned salmon for salmon and potato recipes?", a: "Yes, canned salmon is a great budget-friendly option, especially for fish cakes, chowder, and salads. Drain it well and remove any bones before using." },
      { q: "What herbs go best with salmon and potatoes?", a: "Dill is the classic pairing for salmon. Parsley, chives, tarragon, and thyme also work beautifully. Lemon zest brightens the dish and enhances the natural flavors of the fish." },
    ],
  },
  "pasta-and-tomatoes": {
    title: "6 Easy Recipes with Pasta and Tomatoes (Simple Italian-Inspired Dinners)",
    heading: "6 Easy Recipes with Pasta and Tomatoes",
    intro: "Pasta and tomatoes are at the heart of Italian cooking — and for good reason. Tomatoes provide natural acidity and sweetness that complement pasta in ways no other ingredient can. From a simple pomodoro sauce to a rich Bolognese or a fresh summer pasta salad, this combination is endlessly versatile. Best of all, you probably already have everything you need in your pantry. These easy pasta and tomato recipes will become your go-to weeknight dinners.",
    ingredients: "pasta,tomatoes",
    keywords: ["pasta and tomato recipes", "easy tomato pasta dinner", "simple tomato pasta sauce", "quick pasta with tomatoes", "Italian pasta tomato recipes"],
    tips: [
      "Reserve a cup of pasta water before draining — the starchy water helps bind the sauce to the noodles.",
      "Use canned San Marzano tomatoes for the best flavor in cooked sauces.",
      "Fresh cherry tomatoes burst beautifully in a hot pan and make a quick fresh sauce in minutes.",
      "Cook pasta 1 minute less than the package says and finish it in the sauce to absorb more flavor.",
      "Always salt your pasta water generously — it should taste like mild seawater.",
    ],
    variations: [
      "Pomodoro version: Simmer crushed tomatoes with garlic and olive oil for 15 minutes for a classic sauce.",
      "Fresh version: Toss hot pasta with halved cherry tomatoes, basil, and olive oil for a no-cook sauce.",
      "Baked version: Mix pasta and tomato sauce in a baking dish, top with mozzarella, and bake until bubbly.",
      "Spicy version: Add chili flakes and pancetta to tomato sauce for a quick arrabiata.",
      "Salad version: Toss cooled pasta with fresh tomatoes, olives, feta, and a lemon vinaigrette.",
    ],
    faqs: [
      { q: "What pasta shape works best with tomato sauce?", a: "Spaghetti and penne are classics. Rigatoni and fusilli hold chunky tomato sauces well. For smooth sauces, use long thin pasta like linguine or spaghetti." },
      { q: "Can I use fresh tomatoes instead of canned?", a: "Yes. Use ripe Roma or beefsteak tomatoes for cooked sauces. Blanch and peel them first for a smoother result, or leave the skins on for a more rustic texture." },
      { q: "How do I make tomato sauce less acidic?", a: "Add a pinch of sugar or a small carrot while the sauce cooks to neutralize acidity. A splash of cream or a pat of butter at the end also mellows sharp tomato flavor." },
      { q: "How long does tomato pasta sauce last in the fridge?", a: "Homemade tomato sauce keeps for 4 to 5 days in an airtight container in the fridge. It also freezes well for up to 3 months." },
    ],
  },
  "eggs-and-spinach": {
    title: "6 Easy Recipes with Eggs and Spinach (Healthy Breakfasts & Dinners)",
    heading: "6 Easy Recipes with Eggs and Spinach",
    intro: "Eggs and spinach is one of the most nutritious and versatile combinations in the kitchen. Whether you are making a quick scramble for breakfast, a frittata for brunch, or a light dinner, eggs and spinach come together in minutes and deliver a meal packed with protein, iron, and vitamins. Spinach wilts down dramatically when cooked, making it easy to pack a large amount of nutrition into any dish. Here are the best easy eggs and spinach recipes for any time of day.",
    ingredients: "eggs,spinach",
    keywords: ["eggs and spinach recipes", "spinach egg breakfast", "easy eggs and spinach dinner", "spinach scrambled eggs", "healthy egg and spinach meals"],
    tips: [
      "Wilt spinach in the pan for just 1 to 2 minutes before adding eggs — it cooks down quickly.",
      "Use fresh baby spinach for the best texture and flavor in egg dishes.",
      "Season eggs with salt only after cooking to prevent them from becoming watery.",
      "Add a splash of water rather than milk to scrambled eggs for a fluffier texture.",
      "Frozen spinach works in frittatas and baked egg dishes — just squeeze out all excess water first.",
    ],
    variations: [
      "Scramble version: Wilt spinach in butter, pour in beaten eggs, scramble gently over low heat.",
      "Frittata version: Cook spinach in an oven-safe pan, add beaten eggs and cheese, finish under the broiler.",
      "Shakshuka version: Simmer spinach in spiced tomato sauce and poach eggs directly in the sauce.",
      "Omelette version: Fill a classic French omelette with sauteed spinach and feta cheese.",
      "Baked version: Layer spinach in a baking dish, crack eggs on top, bake at 375F until whites are set.",
    ],
    faqs: [
      { q: "Does spinach go well with eggs?", a: "Yes, spinach and eggs are a classic pairing. Spinach adds a mild earthy flavor, nutrients, and color to egg dishes without overpowering the egg flavor." },
      { q: "How much spinach do I need per serving?", a: "Fresh spinach wilts down to about a quarter of its original volume. Use about 2 cups of fresh spinach per serving, which will wilt to roughly half a cup after cooking." },
      { q: "Can I use frozen spinach with eggs?", a: "Yes, but always thaw and squeeze out as much water as possible before cooking. Excess moisture will make your eggs watery and prevent proper browning." },
      { q: "What cheese goes well with eggs and spinach?", a: "Feta, goat cheese, gruyere, and parmesan all pair beautifully. Feta is especially popular as its salty, tangy flavor complements both eggs and spinach perfectly." },
    ],
  },
  "chicken-and-carrots": {
    title: "6 Easy Recipes with Chicken and Carrots (Hearty & Wholesome Dinners)",
    heading: "6 Easy Recipes with Chicken and Carrots",
    intro: "Chicken and carrots is a classic comfort food pairing found in soups, stews, roasts, and one-pan dinners across countless cuisines. Carrots add natural sweetness, color, and nutrition to any chicken dish, while their firm texture holds up well during long cooking times. Whether you are making a quick weeknight stir fry or a slow-cooked Sunday stew, chicken and carrots deliver wholesome, satisfying results every time.",
    ingredients: "chicken,carrots",
    keywords: ["chicken and carrot recipes", "easy chicken carrot dinner", "chicken carrot soup", "roast chicken with carrots", "healthy chicken and carrot meals"],
    tips: [
      "Cut carrots into similar-sized pieces for even cooking throughout the dish.",
      "Roasting carrots brings out their natural sweetness — use high heat and a little olive oil.",
      "Add carrots early in soups and stews as they take longer to soften than most vegetables.",
      "Glaze roasted carrots with a little honey or maple syrup for a beautiful caramelized finish.",
      "Baby carrots are a convenient shortcut and work perfectly in any chicken and carrot recipe.",
    ],
    variations: [
      "Soup version: Simmer chicken thighs with carrots, celery, and onion in broth for a classic chicken soup.",
      "Roast version: Season chicken pieces and whole carrots with herbs, roast together at 400F for 45 minutes.",
      "Stir fry version: Cook sliced chicken and julienned carrots with soy sauce, ginger, and sesame oil.",
      "Stew version: Braise chicken thighs with carrots, potatoes, and herbs in white wine and broth.",
      "Sheet pan version: Toss with olive oil and cumin, roast at 425F for 30 minutes for a simple weeknight dinner.",
    ],
    faqs: [
      { q: "Do chicken and carrots cook at the same rate?", a: "Not always. Carrots take longer to soften than chicken takes to cook through. Cut carrots smaller than chicken pieces, or give them a head start in the pan or oven." },
      { q: "What herbs go best with chicken and carrots?", a: "Thyme, rosemary, and parsley are classic choices. Tarragon pairs especially well with chicken and carrots in French-style dishes. Cumin and coriander work great for a Moroccan twist." },
      { q: "Can I use frozen carrots in chicken recipes?", a: "Yes, frozen carrots work well in soups and stews where texture is less critical. For roasting or stir frying, fresh carrots give better results as frozen ones can become mushy." },
      { q: "How do I make chicken and carrot soup from scratch?", a: "Simmer a whole chicken or bone-in pieces with carrots, celery, onion, garlic, and herbs in water for 45 minutes. Remove chicken, shred the meat, return to the pot, and season with salt and pepper." },
    ],
  },
  "beef-and-mushrooms": {
    title: "6 Easy Recipes with Beef and Mushrooms (Rich & Savory Dinners)",
    heading: "6 Easy Recipes with Beef and Mushrooms",
    intro: "Beef and mushrooms is one of the most deeply satisfying flavor combinations in cooking. Mushrooms have a natural umami quality that intensifies and enhances the savory flavor of beef, creating dishes that taste rich and complex even with minimal ingredients. From a classic beef stroganoff to a hearty stew or a simple pan sauce, this pairing elevates any meal. If you have beef and mushrooms on hand, you are just a short time away from an exceptional dinner.",
    ingredients: "beef,mushrooms",
    keywords: ["beef and mushroom recipes", "easy beef mushroom dinner", "beef mushroom stroganoff", "beef mushroom stew", "savory beef and mushroom meals"],
    tips: [
      "Cook mushrooms in a dry hot pan first without oil to drive off moisture and develop deep flavor.",
      "Do not crowd mushrooms in the pan — cook in batches to get browning rather than steaming.",
      "Add a splash of Worcestershire sauce to beef and mushroom dishes for extra depth.",
      "Use a mix of mushroom varieties like cremini, shiitake, and portobello for more complex flavor.",
      "Deglaze the pan with red wine or beef broth after browning beef to capture all the flavorful bits.",
    ],
    variations: [
      "Stroganoff version: Cook beef strips and mushrooms in a sour cream sauce, serve over egg noodles.",
      "Stew version: Braise beef chunks with mushrooms, onions, and red wine for 2 hours until tender.",
      "Stir fry version: Cook thinly sliced beef with mushrooms and oyster sauce over high heat.",
      "Burger version: Top beef patties with sauteed mushrooms and Swiss cheese for an umami-packed burger.",
      "Pasta version: Toss cooked pasta with beef and mushroom ragu for a hearty Italian-inspired meal.",
    ],
    faqs: [
      { q: "What type of mushroom works best with beef?", a: "Cremini and portobello mushrooms have the most robust flavor and hold up well with beef. Shiitake adds a smoky depth. Button mushrooms are mild but absorb beef flavor beautifully during cooking." },
      { q: "How do I get mushrooms to brown properly?", a: "Use a hot, dry pan and avoid stirring too much. Cook in a single layer without crowding. Only add butter or oil after the mushrooms have released their moisture and started to brown." },
      { q: "What cut of beef works best with mushrooms?", a: "For quick cooking, use sirloin, flank steak, or beef tenderloin sliced thin. For stews and braises, chuck roast or short ribs become incredibly tender and flavorful with mushrooms." },
      { q: "Can I make beef and mushroom dishes ahead of time?", a: "Yes, stews and braises actually taste better the next day as the flavors meld. Refrigerate for up to 4 days or freeze for up to 3 months. Reheat gently on the stovetop with a splash of broth." },
    ],
  },
  "tuna-and-rice": {
    title: "6 Easy Recipes with Tuna and Rice (Budget-Friendly Dinners)",
    heading: "6 Easy Recipes with Tuna and Rice",
    intro: "Tuna and rice is one of the most budget-friendly and nutritious meal combinations you can make. Canned tuna is a pantry staple that is high in protein and ready in seconds, while rice provides a filling, versatile base. Together they form the foundation for everything from simple tuna rice bowls to Japanese-inspired sushi bowls and hearty casseroles. If you have tuna and rice at home, a quick and satisfying dinner is always within reach.",
    ingredients: "tuna,rice",
    keywords: ["tuna and rice recipes", "easy tuna rice dinner", "canned tuna and rice meals", "tuna rice bowl", "budget tuna rice recipes"],
    tips: [
      "Drain canned tuna thoroughly before using to prevent dishes from becoming watery.",
      "Season tuna rice bowls with soy sauce, sesame oil, and sriracha for a quick Japanese-inspired meal.",
      "Mix tuna with mayo, lemon juice, and dill for a classic filling to serve over rice.",
      "Use leftover rice for tuna fried rice — day-old rice fries much better than freshly cooked.",
      "Rinse canned tuna under cold water to remove any excess sodium or oil.",
    ],
    variations: [
      "Bowl version: Serve seasoned tuna over steamed rice with avocado, cucumber, and soy sauce.",
      "Fried rice version: Stir fry day-old rice with tuna, eggs, peas, and soy sauce.",
      "Casserole version: Mix tuna and rice with cream of mushroom soup, top with breadcrumbs, bake at 350F.",
      "Sushi bowl version: Season rice with rice vinegar, top with tuna, nori, sesame seeds, and pickled ginger.",
      "Salad version: Toss cooled rice with tuna, corn, red onion, and a light lemon vinaigrette.",
    ],
    faqs: [
      { q: "What type of canned tuna is best for rice dishes?", a: "Chunk light tuna in water is the most versatile and budget-friendly option. Solid white albacore has a milder flavor and firmer texture. For sushi-style bowls, use sashimi-grade fresh tuna." },
      { q: "Can I use tuna in oil instead of water?", a: "Yes, tuna in oil has more flavor and a richer texture. Drain it well before using. It works especially well in Mediterranean-style dishes and pasta recipes." },
      { q: "How do I make tuna fried rice?", a: "Cook day-old rice in a hot wok with oil, add beaten eggs and scramble, toss in drained tuna with soy sauce, sesame oil, and green onions. Cook on high heat for 3 to 4 minutes." },
      { q: "Is tuna and rice healthy?", a: "Yes, it is a protein-rich, balanced meal. Tuna is high in lean protein and omega-3 fatty acids. Pair with brown rice for extra fiber. Limit to 2 to 3 servings of canned tuna per week due to mercury content." },
    ],
  },
  "chicken-and-corn": {
    title: "6 Easy Recipes with Chicken and Corn (Sweet & Savory Dinners)",
    heading: "6 Easy Recipes with Chicken and Corn",
    intro: "Chicken and corn is a sweet and savory combination that works beautifully in soups, chowders, tacos, salads, and stir fries. Corn adds natural sweetness, color, and texture to any chicken dish, and it pairs well with a huge range of seasonings from Mexican spices to Asian sauces. Both fresh and canned corn work perfectly, making this an easy combination to pull together any night of the week.",
    ingredients: "chicken,corn",
    keywords: ["chicken and corn recipes", "easy chicken corn dinner", "chicken corn soup", "chicken corn chowder", "quick chicken and corn meals"],
    tips: [
      "Char corn in a dry hot cast iron pan for a smoky, sweet flavor that elevates any dish.",
      "Frozen corn is just as nutritious as fresh and works perfectly in soups and stir fries.",
      "Canned corn should be drained and rinsed before using for the best flavor.",
      "Add corn at the end of cooking soups and stews to keep it tender rather than mushy.",
      "Corn pairs especially well with smoked paprika, cumin, and lime for a Mexican-inspired flavor profile.",
    ],
    variations: [
      "Chowder version: Simmer chicken and corn with potatoes, cream, and herbs for a hearty soup.",
      "Taco version: Season shredded chicken with cumin and chili powder, serve with corn and avocado in tortillas.",
      "Stir fry version: Cook chicken strips with corn, bell peppers, and soy sauce for a quick meal.",
      "Salad version: Grill chicken and toss with corn, black beans, tomatoes, and a lime vinaigrette.",
      "Casserole version: Layer chicken, corn, and cheese in a baking dish with a cornbread topping.",
    ],
    faqs: [
      { q: "Can I use canned corn in chicken recipes?", a: "Absolutely. Canned corn is convenient and works well in soups, stews, casseroles, and stir fries. Just drain and rinse it before using to remove excess sodium." },
      { q: "What seasoning goes best with chicken and corn?", a: "Mexican spices like cumin, chili powder, and smoked paprika are classic pairings. Garlic, lime, and cilantro also work beautifully. For an Asian twist, try soy sauce, ginger, and sesame oil." },
      { q: "How do I char corn without a grill?", a: "Heat a dry cast iron skillet over high heat. Add corn kernels in a single layer without stirring for 2 to 3 minutes until charred on one side, then toss. This takes about 5 to 6 minutes total." },
      { q: "What goes well with chicken and corn?", a: "Black beans, avocado, bell peppers, and cheese are natural pairings. Rice and tortillas make great bases. A squeeze of fresh lime brings the whole dish together." },
    ],
  },
  "shrimp-and-broccoli": {
    title: "6 Easy Recipes with Shrimp and Broccoli (Healthy Quick Dinners)",
    heading: "6 Easy Recipes with Shrimp and Broccoli",
    intro: "Shrimp and broccoli is one of the most popular takeout combinations — and it is even better and healthier when made at home. Both ingredients cook in just minutes, making this an ideal weeknight dinner when you are short on time. Shrimp provides lean protein while broccoli adds fiber, vitamins, and a satisfying crunch. Together they make a complete, balanced meal with minimal effort.",
    ingredients: "shrimp,broccoli",
    keywords: ["shrimp and broccoli recipes", "easy shrimp broccoli stir fry", "healthy shrimp broccoli dinner", "quick shrimp and broccoli", "shrimp broccoli garlic"],
    tips: [
      "Blanch broccoli for 90 seconds before stir frying to get the perfect crisp-tender texture.",
      "Cook shrimp and broccoli separately and combine at the end to prevent overcooking either one.",
      "Use high heat for stir frying — this is essential for proper searing rather than steaming.",
      "Pat shrimp completely dry before cooking for the best sear and texture.",
      "A simple sauce of soy sauce, garlic, ginger, and a little honey brings everything together.",
    ],
    variations: [
      "Stir fry version: Cook in a wok with garlic, soy sauce, sesame oil, and oyster sauce over high heat.",
      "Garlic butter version: Saute in garlic butter with lemon juice, serve over rice or pasta.",
      "Pasta version: Toss shrimp, broccoli, and garlic with olive oil and parmesan over spaghetti.",
      "Sheet pan version: Season with olive oil and garlic, roast together at 425F for 12 to 15 minutes.",
      "Soup version: Simmer in a light broth with ginger, garlic, and noodles for an Asian-style soup.",
    ],
    faqs: [
      { q: "How do I prevent shrimp from overcooking in a stir fry?", a: "Add shrimp last in the cooking process and cook for only 2 minutes per side until pink and curled into a C shape. Remove immediately from heat — they will continue cooking from residual heat." },
      { q: "Should I use fresh or frozen broccoli with shrimp?", a: "Fresh broccoli gives the best texture for stir fries. Frozen broccoli can become too soft when stir fried but works well in soups and baked dishes." },
      { q: "What sauce goes best with shrimp and broccoli?", a: "A classic stir fry sauce of soy sauce, garlic, ginger, and a little cornstarch works perfectly. Oyster sauce adds depth. Garlic butter with lemon is excellent for a non-Asian version." },
      { q: "Is shrimp and broccoli healthy?", a: "Yes, it is an excellent low-calorie, high-protein meal. Shrimp is very low in fat and calories while being high in protein. Broccoli is rich in vitamins C and K, fiber, and antioxidants." },
    ],
  },
  "ground-beef-and-tomatoes": {
    title: "6 Easy Recipes with Ground Beef and Tomatoes (Classic Comfort Dinners)",
    heading: "6 Easy Recipes with Ground Beef and Tomatoes",
    intro: "Ground beef and tomatoes is one of the most classic and versatile combinations in home cooking. Whether you are making a simple meat sauce for pasta, a hearty chili, stuffed peppers, or tacos, these two ingredients form the backbone of dozens of beloved recipes. Tomatoes add acidity, sweetness, and moisture that balance the richness of ground beef perfectly. If you have ground beef and tomatoes at home, a satisfying dinner is never far away.",
    ingredients: "ground beef,tomatoes",
    keywords: ["ground beef and tomato recipes", "easy ground beef tomato dinner", "ground beef tomato sauce", "ground beef tomato pasta", "simple ground beef tomato meals"],
    tips: [
      "Brown ground beef in batches over high heat to get proper caramelization and better flavor.",
      "Add canned crushed tomatoes for a smoother sauce, diced tomatoes for a chunkier texture.",
      "Let the tomato sauce simmer for at least 20 minutes to develop deep, rich flavor.",
      "Add a pinch of sugar to balance the acidity of tomatoes in meat sauces.",
      "Drain excess fat from browned beef before adding tomatoes for a less greasy sauce.",
    ],
    variations: [
      "Pasta sauce version: Simmer browned beef with crushed tomatoes, garlic, and Italian herbs for 30 minutes.",
      "Chili version: Add kidney beans, chili powder, cumin, and beef broth, simmer 45 minutes.",
      "Stuffed peppers version: Fill halved bell peppers with seasoned beef and tomato mixture, bake at 375F.",
      "Taco version: Season beef with cumin and chili powder, serve with diced tomatoes in tortillas.",
      "Soup version: Add beef broth, vegetables, and pasta for a quick minestrone-style soup.",
    ],
    faqs: [
      { q: "Can I use fresh tomatoes instead of canned for ground beef dishes?", a: "Yes. Use ripe Roma or plum tomatoes for the best results. Chop finely and cook down for 20 to 30 minutes to develop a sauce-like consistency. Canned tomatoes are more convenient and consistent." },
      { q: "What is the best way to season ground beef and tomatoes?", a: "Italian herbs like basil, oregano, and thyme work for pasta sauces. Mexican spices like cumin, chili powder, and garlic work for tacos and chili. A bay leaf adds depth to any slow-cooked tomato and beef dish." },
      { q: "How do I make ground beef and tomato sauce from scratch?", a: "Brown beef in a pan, drain fat, add garlic and cook 1 minute, pour in crushed tomatoes, season with herbs, and simmer on low for 20 to 30 minutes. Adjust seasoning and serve over pasta or rice." },
      { q: "How long does ground beef tomato sauce keep?", a: "It keeps in the fridge for 4 days in an airtight container and freezes well for up to 3 months. This makes it an excellent recipe to batch cook and freeze for quick future meals." },
    ],
  },
  "pasta-and-mushrooms": {
    title: "6 Easy Recipes with Pasta and Mushrooms (Rich & Earthy Dinners)",
    heading: "6 Easy Recipes with Pasta and Mushrooms",
    intro: "Pasta and mushrooms is a match made in culinary heaven. Mushrooms bring an earthy, umami-rich depth to pasta dishes that makes them taste luxurious even without meat. Whether you are making a simple garlic mushroom pasta, a creamy mushroom sauce, or a hearty mushroom ragu, this combination delivers restaurant-quality results at home in under 30 minutes. It is also naturally vegetarian, making it perfect for meatless meals that everyone will love.",
    ingredients: "pasta,mushrooms",
    keywords: ["pasta and mushroom recipes", "easy mushroom pasta dinner", "creamy mushroom pasta", "garlic mushroom pasta", "vegetarian mushroom pasta"],
    tips: [
      "Cook mushrooms in a hot dry pan first to drive off moisture before adding butter or oil.",
      "Use a mix of mushroom varieties for more complex flavor — cremini, shiitake, and oyster work great together.",
      "Reserve pasta water to loosen the sauce and help it cling to the noodles.",
      "Add fresh thyme or rosemary to mushrooms as they cook for an aromatic depth.",
      "Finish the dish with a drizzle of truffle oil for an elevated, restaurant-quality flavor.",
    ],
    variations: [
      "Creamy version: Cook mushrooms in butter, add cream and parmesan, toss with fettuccine.",
      "Garlic version: Saute mushrooms with lots of garlic and olive oil, toss with spaghetti and parsley.",
      "Ragu version: Finely chop mushrooms and cook slowly with tomatoes and herbs for a meaty vegetarian sauce.",
      "Baked version: Mix pasta and mushroom cream sauce in a baking dish, top with breadcrumbs and bake.",
      "Asian version: Toss pasta with sauteed mushrooms, soy sauce, sesame oil, and green onions.",
    ],
    faqs: [
      { q: "What pasta shape works best with mushrooms?", a: "Wide, flat noodles like pappardelle and fettuccine hold creamy mushroom sauces beautifully. Rigatoni and penne work well for chunkier mushroom sauces. Spaghetti pairs nicely with light, garlic-based mushroom preparations." },
      { q: "How do I get mushrooms to brown properly for pasta?", a: "Use a very hot, dry pan. Add mushrooms in a single layer without stirring for 2 to 3 minutes. Only flip once they have developed a golden-brown crust. Avoid crowding the pan." },
      { q: "What mushrooms are best for pasta?", a: "Cremini mushrooms are versatile and widely available. Porcini (fresh or dried) add intense earthy flavor. Shiitake brings a smoky depth. Oyster mushrooms have a delicate, silky texture that works beautifully in cream sauces." },
      { q: "Can I make mushroom pasta ahead of time?", a: "The sauce can be made ahead and refrigerated for 2 to 3 days. Cook the pasta fresh when serving to prevent it from becoming soggy. Reheat the sauce gently with a splash of cream or pasta water." },
    ],
  },
  "chicken-and-beans": {
    title: "6 Easy Recipes with Chicken and Beans (Hearty & Budget-Friendly)",
    heading: "6 Easy Recipes with Chicken and Beans",
    intro: "Chicken and beans is one of the most nutritious, budget-friendly, and satisfying meal combinations you can make. Beans are packed with fiber, plant protein, and complex carbohydrates that make any meal more filling and nutritious. Together with chicken, they create hearty dishes like soups, stews, chilis, and casseroles that stretch your grocery budget without sacrificing flavor. Any type of bean works beautifully — black beans, white beans, chickpeas, or kidney beans.",
    ingredients: "chicken,beans",
    keywords: ["chicken and bean recipes", "easy chicken bean dinner", "chicken white bean soup", "chicken black bean recipes", "healthy chicken and bean meals"],
    tips: [
      "Canned beans save significant time — drain and rinse well before adding to any recipe.",
      "White beans break down slightly when cooked, naturally thickening soups and stews.",
      "Add beans in the last 15 minutes of cooking stews to keep their shape and texture.",
      "Mash a portion of the beans against the pot wall to thicken soups without adding cream.",
      "Season beans well — they absorb flavors beautifully but need generous seasoning.",
    ],
    variations: [
      "Soup version: Simmer chicken thighs with white beans, kale, garlic, and chicken broth for a Tuscan-style soup.",
      "Chili version: Use shredded chicken with black beans, tomatoes, and chili spices for a white or red chili.",
      "Casserole version: Mix chicken, beans, and salsa in a baking dish, top with cheese and bake at 375F.",
      "Taco version: Serve seasoned shredded chicken with black beans in tortillas with salsa and guacamole.",
      "Stew version: Braise chicken thighs with chickpeas, tomatoes, and Moroccan spices for a warming tagine.",
    ],
    faqs: [
      { q: "What beans go best with chicken?", a: "White beans like cannellini pair beautifully in Italian-style soups and stews. Black beans are classic in Mexican-inspired dishes. Chickpeas work well in Moroccan and Mediterranean recipes. Kidney beans are great in chili." },
      { q: "Can I use dried beans instead of canned?", a: "Yes, but soak dried beans overnight and cook for 1 to 2 hours before adding to recipes. Canned beans are pre-cooked and ready to use, making them much more convenient for weeknight cooking." },
      { q: "How do I make chicken and bean soup?", a: "Saute onion, garlic, and carrots, add chicken broth and chicken, simmer 25 minutes, shred chicken, add rinsed beans and greens, season with salt, pepper, and herbs, simmer 10 more minutes." },
      { q: "Is chicken and beans a complete protein?", a: "Yes, together chicken and beans provide all essential amino acids along with fiber, vitamins, and minerals, making this one of the most nutritionally complete meal combinations you can eat." },
    ],
  },
  "eggs-and-mushrooms": {
    title: "6 Easy Recipes with Eggs and Mushrooms (Savory Any-Time Meals)",
    heading: "6 Easy Recipes with Eggs and Mushrooms",
    intro: "Eggs and mushrooms is a deeply savory, satisfying combination that works beautifully at breakfast, brunch, lunch, or dinner. Mushrooms bring an earthy, umami-rich flavor that pairs perfectly with the mild creaminess of eggs. Whether you are making a simple scramble, a hearty frittata, or an elegant stuffed mushroom dish, this pairing is quick to prepare and endlessly versatile. Here are the best easy eggs and mushroom recipes for any time of day.",
    ingredients: "eggs,mushrooms",
    keywords: ["eggs and mushroom recipes", "mushroom egg breakfast", "easy eggs and mushroom dinner", "mushroom scrambled eggs", "mushroom frittata recipe"],
    tips: [
      "Saute mushrooms first until golden before adding eggs — this prevents a watery final dish.",
      "Use butter rather than oil for sauteing mushrooms to get the richest flavor with eggs.",
      "Add fresh thyme or chives to mushrooms and eggs for an elevated, aromatic flavor.",
      "Cook eggs low and slow for the creamiest scramble when paired with mushrooms.",
      "A splash of cream or creme fraiche stirred into scrambled eggs with mushrooms adds luxurious richness.",
    ],
    variations: [
      "Scramble version: Saute mushrooms in butter, add beaten eggs, scramble gently over low heat with fresh herbs.",
      "Frittata version: Cook mushrooms in an oven-safe pan, pour over beaten eggs and cheese, broil until set.",
      "Omelette version: Fill a classic omelette with sauteed mushrooms, cheese, and fresh thyme.",
      "Baked version: Stuff mushroom caps with a mixture of egg, cheese, and herbs, bake at 375F for 20 minutes.",
      "Toast version: Pile sauteed mushrooms over poached eggs on thick sourdough toast.",
    ],
    faqs: [
      { q: "What mushrooms work best with eggs?", a: "Button and cremini mushrooms are the most accessible and versatile. Shiitake adds a smoky depth. Oyster mushrooms have a delicate flavor and silky texture. Portobello caps make excellent vessels for baked egg dishes." },
      { q: "How do I prevent mushrooms from making eggs watery?", a: "Cook mushrooms thoroughly in a hot pan until all moisture has evaporated and they are golden brown before adding eggs. Never add raw mushrooms directly to eggs." },
      { q: "Can I add cheese to eggs and mushrooms?", a: "Absolutely. Gruyere, parmesan, goat cheese, and brie all pair beautifully with mushrooms and eggs. Add cheese at the end of cooking to prevent it from becoming rubbery." },
      { q: "Are eggs and mushrooms good for you?", a: "Yes, this is a very nutritious combination. Eggs provide complete protein and healthy fats. Mushrooms are low in calories but rich in B vitamins, vitamin D, selenium, and antioxidants." },
    ],
  },
  "salmon-and-lemon": {
    title: "6 Easy Recipes with Salmon and Lemon (Bright & Healthy Dinners)",
    heading: "6 Easy Recipes with Salmon and Lemon",
    intro: "Salmon and lemon is one of the most natural and beloved flavor pairings in all of cooking. Lemon's bright acidity cuts through the richness of salmon perfectly, bringing out the fresh, clean flavor of the fish without overpowering it. Whether you are baking, pan frying, grilling, or poaching, a squeeze of lemon transforms salmon from good to extraordinary. These easy salmon and lemon recipes are healthy, elegant, and ready in under 30 minutes.",
    ingredients: "salmon,lemon",
    keywords: ["salmon and lemon recipes", "lemon salmon recipe", "easy lemon baked salmon", "healthy salmon lemon dinner", "quick salmon and lemon meals"],
    tips: [
      "Use both lemon juice and lemon zest for maximum lemon flavor in salmon dishes.",
      "Marinate salmon in lemon juice for no more than 30 minutes — longer will begin to cook the fish.",
      "Place lemon slices under the salmon while baking to infuse flavor from below.",
      "Squeeze fresh lemon over cooked salmon just before serving for the brightest flavor.",
      "Brown butter with lemon is one of the simplest and most delicious sauces for pan-seared salmon.",
    ],
    variations: [
      "Baked version: Place salmon on lemon slices, drizzle with olive oil and herbs, bake at 400F for 12 to 15 minutes.",
      "Pan seared version: Sear skin-side down 4 minutes, flip 2 minutes, finish with lemon butter sauce.",
      "Grilled version: Marinate in lemon, garlic, and olive oil, grill 3 to 4 minutes per side.",
      "Poached version: Simmer salmon in water with lemon slices, dill, and white wine until just cooked through.",
      "Pasta version: Flake cooked lemon salmon into pasta with capers, olive oil, and fresh parsley.",
    ],
    faqs: [
      { q: "How much lemon should I use with salmon?", a: "A good rule of thumb is half a lemon per salmon fillet. Use the juice for cooking or marinating and the zest for garnishing or adding to sauces for bright flavor without extra acidity." },
      { q: "Should I put lemon on salmon before or after cooking?", a: "Both. Marinate with lemon briefly before cooking for flavor penetration. Add fresh lemon juice after cooking to brighten the finished dish. Avoid cooking with too much lemon juice as it can make the fish tough." },
      { q: "What herbs go best with lemon salmon?", a: "Dill is the classic choice and complements both salmon and lemon beautifully. Parsley, chives, tarragon, and basil also work well. Thyme and rosemary pair nicely in Mediterranean-style preparations." },
      { q: "How do I know when lemon salmon is done?", a: "The flesh should flake easily with a fork and be opaque throughout. The internal temperature should reach 145F for food safety, though many prefer it at 125 to 130F for a silkier texture." },
    ],
  },
  "beef-and-carrots": {
    title: "6 Easy Recipes with Beef and Carrots (Hearty Comfort Food Dinners)",
    heading: "6 Easy Recipes with Beef and Carrots",
    intro: "Beef and carrots is the ultimate comfort food pairing — warm, hearty, and deeply satisfying. Carrots add natural sweetness that balances the savory richness of beef, and their firm texture holds up beautifully in slow-cooked stews, braises, and roasts. This classic combination is at the heart of pot roast, beef stew, and Bolognese, making it one of the most beloved pairings in home cooking. If you have beef and carrots, a truly comforting dinner is just ahead.",
    ingredients: "beef,carrots",
    keywords: ["beef and carrot recipes", "easy beef carrot dinner", "beef carrot stew", "pot roast with carrots", "hearty beef and carrot meals"],
    tips: [
      "Cut carrots into large chunks for stews so they hold their shape during long cooking.",
      "Add carrots in the last 45 minutes of braising to prevent them from becoming mushy.",
      "Brown beef well before adding carrots and liquid — this develops the deepest flavor.",
      "A splash of red wine adds wonderful depth to beef and carrot braises and stews.",
      "Baby carrots are a convenient option and require no chopping for quick weeknight dinners.",
    ],
    variations: [
      "Stew version: Braise beef chunks with carrots, potatoes, and herbs in beef broth for 2 hours.",
      "Pot roast version: Slow cook a beef roast with carrots and onions in the oven at 325F for 3 to 4 hours.",
      "Stir fry version: Cook thinly sliced beef with julienned carrots in soy sauce and ginger.",
      "Soup version: Simmer beef with carrots, celery, and barley in broth for a hearty winter soup.",
      "Sheet pan version: Roast beef strips and carrot coins with olive oil and herbs at 425F for 25 minutes.",
    ],
    faqs: [
      { q: "What cut of beef works best with carrots?", a: "Chuck roast is the classic choice for braises and pot roast as it becomes incredibly tender with slow cooking. Short ribs are also excellent. For quick stir fries, use flank steak or sirloin sliced thin against the grain." },
      { q: "How long should I braise beef and carrots?", a: "Chuck roast needs 2.5 to 3.5 hours in a 325F oven or on low in a slow cooker for 8 hours. Add carrots in the last 45 minutes to prevent them from overcooking and becoming mushy." },
      { q: "What liquid should I use for beef and carrot braise?", a: "Beef broth is the foundation. Red wine adds depth and richness. Tomato paste stirred in at the beginning builds umami. A combination of broth and red wine is the most flavorful option." },
      { q: "Can I make beef and carrot stew in a slow cooker?", a: "Yes, it is ideal for slow cookers. Brown the beef first in a pan for better flavor, then add to the slow cooker with carrots, broth, and herbs. Cook on low for 8 hours or high for 4 to 5 hours." },
    ],
  },
  "chicken-and-avocado": {
    title: "6 Easy Recipes with Chicken and Avocado (Fresh & Healthy Meals)",
    heading: "6 Easy Recipes with Chicken and Avocado",
    intro: "Chicken and avocado is a fresh, healthy, and incredibly satisfying combination. Avocado adds creamy richness, healthy fats, and a buttery texture that complements grilled, baked, or shredded chicken beautifully. From salads and wraps to bowls and tacos, this pairing is popular for good reason — it is delicious, nutritious, and comes together quickly. These easy chicken and avocado recipes are perfect for light lunches and healthy weeknight dinners.",
    ingredients: "chicken,avocado",
    keywords: ["chicken and avocado recipes", "easy chicken avocado dinner", "chicken avocado salad", "healthy chicken avocado meals", "chicken avocado bowl"],
    tips: [
      "Add avocado at the very end of cooking or just before serving to prevent browning.",
      "Squeeze lime or lemon juice over cut avocado immediately to slow oxidation.",
      "Grilled chicken pairs especially well with avocado due to its smoky, charred flavor.",
      "Mash avocado with lime and salt for a quick guacamole-style sauce to top chicken.",
      "Slice avocado thick for salads and bowls so it holds its shape and texture.",
    ],
    variations: [
      "Salad version: Toss sliced grilled chicken with avocado, cherry tomatoes, and a lime vinaigrette.",
      "Wrap version: Fill a tortilla with sliced chicken, avocado, greens, and salsa.",
      "Bowl version: Serve seasoned chicken over rice with avocado, cucumber, and a soy-sesame dressing.",
      "Taco version: Top corn tortillas with shredded chicken, avocado slices, and pickled red onion.",
      "Stuffed version: Fill avocado halves with seasoned chicken salad for a low-carb, protein-rich meal.",
    ],
    faqs: [
      { q: "How do I keep avocado from browning in chicken dishes?", a: "Add avocado just before serving. If preparing ahead, toss avocado in lime or lemon juice, press plastic wrap directly onto the surface, and refrigerate. Use within a few hours for best color." },
      { q: "What seasoning works best with chicken and avocado?", a: "Lime, garlic, cumin, and cilantro are a classic Mexican-inspired combination. Simple olive oil, salt, and pepper let both ingredients shine. A pinch of chili flakes adds a nice kick." },
      { q: "Can I cook avocado with chicken?", a: "You can briefly warm avocado but it should not be cooked for long as heat makes it bitter and mushy. Add avocado slices to a warm dish right before serving, or use it as a cool contrast to hot chicken." },
      { q: "Is chicken and avocado healthy?", a: "Yes, it is excellent nutritionally. Chicken provides lean protein and avocado supplies healthy monounsaturated fats, fiber, potassium, and vitamins C, E, K, and B6. Together they make a nutrient-dense, satisfying meal." },
    ],
  },'''

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

# Find the insertion point — before the closing of slugData
marker = '  "shrimp-and-pasta": {'
if marker not in content:
    print("ERROR: Could not find insertion marker 'shrimp-and-pasta'")
else:
    content = content.replace(marker, new_slugs + '\n  "shrimp-and-pasta": {', 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("Done! 20 new slug entries added.")
