content = (
    '"use client";\n'
    'import { useState } from "react";\n\n'
    'interface Ingredient {\n'
    '  name: string;\n'
    '}\n\n'
    'interface Recipe {\n'
    '  id: number;\n'
    '  title: string;\n'
    '  image: string;\n'
    '  usedIngredients: Ingredient[];\n'
    '}\n\n'
    'export default function Home() {\n'
    '  const [ingredients, setIngredients] = useState("");\n'
    '  const [recipes, setRecipes] = useState<Recipe[]>([]);\n\n'
    '  const handleSearch = async () => {\n'
    '    const res = await fetch("/api/recipes?ingredients=" + ingredients);\n'
    '    const data = await res.json();\n'
    '    setRecipes(data);\n'
    '  };\n\n'
    '  const getUrl = (recipe: Recipe) => {\n'
    '    return "https://spoonacular.com/recipes/" + recipe.title.replaceAll(" ", "-").toLowerCase() + "-" + recipe.id;\n'
    '  };\n\n'
    '  return (\n'
    '    <main className="min-h-screen p-6 bg-gray-100">\n'
    '      <h1 className="text-3xl font-bold mb-4">Recipe Finder</h1>\n'
    '      <input\n'
    '        type="text"\n'
    '        placeholder="Enter ingredients"\n'
    '        className="border p-2 w-full mb-4 rounded"\n'
    '        value={ingredients}\n'
    '        onChange={(e) => setIngredients(e.target.value)}\n'
    '      />\n'
    '      <button\n'
    '        onClick={handleSearch}\n'
    '        className="bg-black text-white px-4 py-2 rounded mb-6"\n'
    '      >\n'
    '        Find Recipes\n'
    '      </button>\n'
    '      <div className="grid gap-4">\n'
    '        {recipes.map((recipe) => (\n'
    '          <div key={recipe.id} className="bg-white p-4 rounded shadow">\n'
    '            <h2 className="text-xl font-semibold">{recipe.title}</h2>\n'
    '            <img src={recipe.image} alt={recipe.title} className="w-full h-48 object-cover my-2 rounded" />\n'
    '            <p className="text-sm">Ingredients: {recipe.usedIngredients.map((i) => i.name).join(", ")}</p>\n'
    '            <a href={getUrl(recipe)} target="_blank" className="text-blue-600 underline mt-2 block">View Recipe</a>\n'
    '          </div>\n'
    '        ))}\n'
    '      </div>\n'
    '    </main>\n'
    '  );\n'
    '}\n'
)

with open('app/page.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print('Done!')