key = '6b6dd0f982c448f7adef501f6ca84f88'

route = (
    'export async function GET(request) {\n'
    '  const { searchParams } = new URL(request.url);\n'
    '  const ingredients = searchParams.get("ingredients");\n'
    '  const url = "https://api.spoonacular.com/recipes/findByIngredients?ingredients=" + ingredients + "&number=3&apiKey=" + "' + key + '";\n'
    '  try {\n'
    '    const res = await fetch(url);\n'
    '    const data = await res.json();\n'
    '    return Response.json(data);\n'
    '  } catch (error) {\n'
    '    return Response.json({ error: "Failed" }, { status: 500 });\n'
    '  }\n'
    '}\n'
)

page = (
    '"use client";\n'
    'import { useState } from "react";\n\n'
    'export default function Home() {\n'
    '  const [ingredients, setIngredients] = useState("");\n'
    '  const [recipes, setRecipes] = useState([]);\n'
    '  const [loading, setLoading] = useState(false);\n\n'
    '  const handleSearch = async () => {\n'
    '    setLoading(true);\n'
    '    const res = await fetch("/api/recipes?ingredients=" + ingredients);\n'
    '    const data = await res.json();\n'
    '    if (Array.isArray(data)) {\n'
    '      setRecipes(data);\n'
    '    }\n'
    '    setLoading(false);\n'
    '  };\n\n'
    '  return (\n'
    '    <main className="min-h-screen bg-orange-50">\n'
    '      <div className="max-w-2xl mx-auto px-4 py-12">\n'
    '        <h1 className="text-4xl font-bold text-center text-orange-600 mb-2">Recipe Finder</h1>\n'
    '        <p className="text-center text-gray-500 mb-8">Enter ingredients you have and find recipes instantly</p>\n'
    '        <div className="flex gap-2 mb-10">\n'
    '          <input\n'
    '            type="text"\n'
    '            placeholder="e.g. chicken, rice, eggs"\n'
    '            className="flex-1 border-2 border-orange-200 p-3 rounded-xl focus:outline-none focus:border-orange-400 bg-white"\n'
    '            value={ingredients}\n'
    '            onChange={(e) => setIngredients(e.target.value)}\n'
    '          />\n'
    '          <button\n'
    '            onClick={handleSearch}\n'
    '            className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded-xl font-semibold transition-colors"\n'
    '          >\n'
    '            {loading ? "Searching..." : "Find Recipes"}\n'
    '          </button>\n'
    '        </div>\n'
    '        <div className="grid gap-6">\n'
    '          {recipes.map((recipe) => (\n'
    '            <div key={recipe.id} className="bg-white rounded-2xl shadow-md overflow-hidden hover:shadow-lg transition-shadow">\n'
    '              <img src={recipe.image} alt={recipe.title} className="w-full h-52 object-cover" />\n'
    '              <div className="p-5">\n'
    '                <h2 className="text-xl font-bold text-gray-800 mb-2">{recipe.title}</h2>\n'
    '                <p className="text-sm text-gray-500 mb-4">Ingredients used: {recipe.usedIngredients.map((i) => i.name).join(", ")}</p>\n'
    '                <a\n'
    '                  href={"https://spoonacular.com/recipes/" + recipe.title.replaceAll(" ", "-").toLowerCase() + "-" + recipe.id}\n'
    '                  target="_blank"\n'
    '                  className="inline-block bg-orange-100 hover:bg-orange-200 text-orange-700 font-semibold px-4 py-2 rounded-lg transition-colors"\n'
    '                >\n'
    '                  View Full Recipe\n'
    '                </a>\n'
    '              </div>\n'
    '            </div>\n'
    '          ))}\n'
    '        </div>\n'
    '      </div>\n'
    '    </main>\n'
    '  );\n'
    '}\n'
)

with open('app/api/recipes/route.js', 'w', encoding='utf-8') as f:
    f.write(route)

with open('app/page.tsx', 'w', encoding='utf-8') as f:
    f.write(page)

print('Done!')